# Parse VERSION for bundle stem, version_gen.h, and Info.plist placeholders.
file(STRINGS "${CMAKE_SOURCE_DIR}/VERSION" PALETTE_VERSION_LINE LIMIT_COUNT 1)
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${CMAKE_SOURCE_DIR}/VERSION")
string(REGEX REPLACE "\r" "" PALETTE_VERSION_LINE "${PALETTE_VERSION_LINE}")
string(REGEX MATCH "^[0-9]+\\.[0-9]+\\.[0-9]+" PALETTE_TRIPLET "${PALETTE_VERSION_LINE}")
if(NOT PALETTE_TRIPLET)
  message(FATAL_ERROR "VERSION first line must start with major.minor.patch")
endif()

string(LENGTH "${PALETTE_TRIPLET}" _palette_tlen)
string(SUBSTRING "${PALETTE_VERSION_LINE}" "${_palette_tlen}" -1 _palette_rest)
string(STRIP "${_palette_rest}" PALETTE_VERSION_SUFFIX)
if(PALETTE_VERSION_SUFFIX STREQUAL "")
  set(PALETTE_PLUGIN_VERSION_STR "${PALETTE_TRIPLET}")
else()
  set(PALETTE_PLUGIN_VERSION_STR "${PALETTE_TRIPLET} ${PALETTE_VERSION_SUFFIX}")
endif()

string(REPLACE "." ";" _palette_ver_parts "${PALETTE_TRIPLET}")
list(GET _palette_ver_parts 0 PALETTE_VER_MAJOR)
list(GET _palette_ver_parts 1 PALETTE_VER_MINOR)
list(GET _palette_ver_parts 2 PALETTE_VER_PATCH)

set(PALETTE_PLUGIN_DISPLAY "${PALETTE_TRIPLET}")
set(PALETTE_OFX_IDENTIFIER "com.LSP.ColorPalette.${PALETTE_TRIPLET}")
set(PALETTE_OFX_BUNDLE_STEM "LSP_Color_Palette_${PALETTE_PLUGIN_DISPLAY}")
set(PALETTE_OFX_EXECUTABLE_NAME "${PALETTE_OFX_BUNDLE_STEM}.ofx")
set(PALETTE_PLUGIN_ICON_NAME "com.LSP.ColorPalette.${PALETTE_PLUGIN_DISPLAY}.png")
set(PALETTE_RELEASE_FOLDER_MACOS "${PALETTE_OFX_BUNDLE_STEM}_macos")
set(PALETTE_RELEASE_FOLDER_WINDOWS "${PALETTE_OFX_BUNDLE_STEM}_windows")
set(PALETTE_RELEASE_FOLDER_LINUX "${PALETTE_OFX_BUNDLE_STEM}_linux")

set(PALETTE_VERSION_GEN "${CMAKE_SOURCE_DIR}/plugin/version_gen.h")

configure_file(
  "${CMAKE_SOURCE_DIR}/cmake/version_gen.h.in"
  "${PALETTE_VERSION_GEN}"
  @ONLY
)

set(PLUGIN_NUMERIC_VERSION "${PALETTE_TRIPLET}")
set(PLUGIN_DISPLAY_VERSION "${PALETTE_PLUGIN_VERSION_STR}")
set(OFX_EXECUTABLE_NAME "${PALETTE_OFX_EXECUTABLE_NAME}")
set(PLUGIN_OFX_IDENTIFIER "${PALETTE_OFX_IDENTIFIER}")

add_custom_target(colorpalette_gen_version ALL DEPENDS "${PALETTE_VERSION_GEN}")
